### ISSUE TITLE
RDF ACL for node

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#17]
Along with authentication, RDF ACL authorization is an important feature for this server.  Then we will be able to run it facing the open net rather than as a protected proxy.  

The goal would be to make the file structure used on the server  be compatible with gold, so that one could run node-ldp-httpd or gold on the same files and have redundancy of project, and no 'project lock-in'.  

Also of course made sure node-rdf-acl works with any other express systems.

**Comment by martinmr** [comment]
There's a limited ACL that already works (see acl.js). I wrote it using the acl node module but it's quite limited. For example, setting permissions for all users cannot be done with a wildcard. I will look at gold to see how ACL is implemented and write a compatible solution.

**Comment by nicola** [comment]
what is the status of this?

**Comment by martinmr** [comment]
I am working on writing a test suite. The basic tests work.

**Comment by nicola** [comment]
Can we consider this close?
Or otherwise, can we list in this format all the features missing?

```
- [ ] not done
- [x] done
```

**Comment by martinmr** [comment]
It's almost done but all the features involving fetching a graph from a URL currently don't work.

**Comment by deiu** [comment]
From any URL, or just from URLs hosted on servers having self-signed certs?

**Comment by martinmr** [comment]
Actually, it's just https requests that don't work.

There's another bug in the WebID delegation. The test is supposed to add a delegates triple to the user's profile via a POST request. The requests return a 200 status code but the triple is not being added in the databox server so the next test fails but it correctly retrieves the profile (just without the triple that was meant to be added). Not sure how to solve this bug since I am not in control of the databox server.

**Comment by martinmr** [comment]
@deiu: I found out what's causing the bug. I found a node library that can do sync requests and the code is correct but the test is hosting the group file in the same folder. Since the acl code is blocking waiting for the response, the server deadlocks when it gets the request for the group file. 

I tested the file by spawning another ldnode server in the same folder but with a different port and retrieving the file from the second server. The acl module correctly retrieves the group file and passes all the tests. However, it's impossible to host the group file in the same server without rewriting the whole module and that would break other features (glob support for example).

I've thought of a workaround: before sending the request, the acl module checks if the domain of the server is the same as its own, and if so reads the file from the filesystem instead of doing a request over the network. I think that would require ldnode to know it's own domain/base URI though so I am not sure how it ties on what we talked about at the last meeting..

**Comment by martinmr** [comment]
Closing for now. PR #87 passes all the tests except for one of the delegation tests which is commented out for now. 

However the code for delegation is correct but it fails because my test users are hosted in databox.me and the server fails to add a delegate triple despite returning a 200 status code. Therefore, this issue is beyond us to fix unless I talk to @deiu or @sandhawke (who I think run the server) or ldnode implements an identity provider.

Everything else works as it should.
