### ISSUE TITLE
Hoisting issues

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#21]
I have seen in this file: https://github.com/linkeddata/ldnode/blob/master/handlers/get.js that the functions `get`, `parseContainer`, `parseLinkedData`, `globHandler`, `containerHandler`, `fileHandler` are declared as anonymous functions and assigned to a variable.

Since they are called before they assigned, this may lead to a `TypeError` or similar issues related to variable hoisting in javascript. http://jamesallardice.com/explaining-function-and-variable-hoisting-in-javascript/

So either we move up the variables, or we declare them, however I think declaring them is not a good idea either.

Instead of declaring them inside a function call (this means 1000 function calls 1000 declarations), we could instead just declare them outside and carry all the variables they need, I assume `req`, `res` being the only two. (This comment is valid for all the other files in /handlers that I have seen)

**Comment by martinmr** [comment]
Thanks for telling me about this. I run into a similar problem earlier which I solved at the time by changing the var declarations to functions? Which is the preferred way to declare function? Should I use var foo = function or function foo()?

I prefer to keep the declarations of helper functions inside rather than having them outside because it clarifies the scope of the function better. 
Would changing
var fileHandler = function(err, data) {
to
function fileHandler(err, data) {
fix the problem?

**Comment by martinmr** [comment]
Closing this issue as it's been addressed in issue #23.
