### ISSUE TITLE
Proxy doesn't seem to work, gives 404

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/ldnode#302]
To reproduce, launch ldnode locally, with a proxy parameter. Try to access an existing URL with that proxy. (Gives a 404).

**Comment by nicola** [comment]
How did you run ldnode?

**Comment by csarven** [comment]
I can confirm that running `--proxy=/proxy` works and `--proxy=proxy` doesn't.

**Comment by sandhawke** [comment]
@csarven I restarted databox2.com with that argument.   Give it a try?

**Comment by nicola** [comment]
I will fix this so that the trailing `/` is not required

**Comment by dmitrizagidulin** [comment]
Ah, ok, yeah, seems to work with the leading slash. Happy to close this issue.

**Comment by csarven** [comment]
Actually, I think it is good to have the trailing slash since it gives a hint as to where it'll be available from. Perhaps the --help  or documentation should be clear. We all missed this "obvious" case so lets take that as a hint to improve. eg:

```
--proxy            Use a proxy on example.tld/proxyPath (eg '/proxyPath')
```

One more step: use default `/proxy` when no value provided with `--proxy`

**Comment by nicola** [comment]
@csarven I think it would be a security issue if I start a proxy on your server by default, is the proxy a mandatory tool in solid?

**Comment by nicola** [comment]
Does #307 work?

**Comment by dmitrizagidulin** [comment]
@nicola - yep, #307 works for me.

As for your other question, is proxy a mandatory tool in solid -- it is for the moment. I don't have any strong feelings about enabling it by default, though. Since clients use databox's proxy by default, it's probably fine either way.

**Comment by sandhawke** [comment]
Hardcoding any centralized server into the client is presumably a very-short-term workaround, and since that seems unnecessary here, I suggest by default proxy be on, unless there's a security risk.   As long as ldnode has a clear warning never to run it behind a firewall, it should be fine, I think.
